language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '12'
  - '13'
  - '14'
script:
  - yarn test:prod && yarn build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: report coverage
      script: yarn report-coverage
    - stage: deploy docs
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy-docs; fi
#    - stage: semantic release
#      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn semantic-release; fi
